// <auto-generated />
using System;
using HekaLojisticsApp.DataAccess.Concrete.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HekaLojisticsApp.DataAccess.Migrations
{
    [DbContext(typeof(LojistikAppContext))]
    [Migration("20211018205009_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HekaLojisticsApp.Entities.Concrete.Order.OrderEntity", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Approval")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BuyerCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("BuyerCustomerAddress1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerCustomerAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerCustomerCityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerCustomerCountryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerCustomerDistrictId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BuyerCustomerFax")
                        .HasColumnType("int");

                    b.Property<int>("BuyerCustomerNumber")
                        .HasColumnType("int");

                    b.Property<int>("BuyerCustomerTaxNumber")
                        .HasColumnType("int");

                    b.Property<int>("BuyerCustomerTaxOffice")
                        .HasColumnType("int");

                    b.Property<string>("BuyerCustomerTitle1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerCustomerTitle2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerRepresentative")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Cancel")
                        .HasColumnType("bit");

                    b.Property<bool>("Closed")
                        .HasColumnType("bit");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CurrencyCode")
                        .HasMaxLength(12)
                        .HasColumnType("int");

                    b.Property<int>("CurrencyKod")
                        .HasColumnType("int");

                    b.Property<string>("CustomerAddress1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerCityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerCountryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerDistrictId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerRepresentative")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerTaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerTaxOffice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerTitle1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerTitle2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeadlineDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryCustomsCode")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("ExitCustomsCode")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("InvoiceStatusCode")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OrderDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<DateTime>("RateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShipperCompanyId")
                        .HasColumnType("int");

                    b.Property<int>("StatusCode")
                        .HasMaxLength(12)
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalVolume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionDirectionCode")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadPointCode")
                        .HasMaxLength(12)
                        .HasColumnType("int");

                    b.Property<int>("UploadTypeCode")
                        .HasMaxLength(12)
                        .HasColumnType("int");

                    b.Property<int>("VolumeUnitCode")
                        .HasMaxLength(12)
                        .HasColumnType("int");

                    b.Property<int>("WeightUnitCode")
                        .HasMaxLength(12)
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("HekaLojisticsApp.Entities.Concrete.Vehicle.VehicleCareEntity", b =>
                {
                    b.Property<int>("VehicleCareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasMaxLength(50)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CareDate")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CurrencyCode")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("KmHour")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("OperationCompanyId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("PersonnelId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VehiceCareTypeId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VehiclePlate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VehicleCareId");

                    b.ToTable("Care", "Vehicle");
                });

            modelBuilder.Entity("HekaLojisticsApp.Entities.Concrete.Vehicle.VehicleCareTypeEntity", b =>
                {
                    b.Property<int>("VehicleCareTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Compulsory")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DefaultPeriyodUnitCode")
                        .HasMaxLength(12)
                        .HasColumnType("int");

                    b.Property<string>("Definition")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VehicleCareTypeId");

                    b.ToTable("CareType", "Vehicle");
                });

            modelBuilder.Entity("HekaLojisticsApp.Entities.Concrete.Vehicle.VehicleEntity", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Approval")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("CareNotification")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("CarePeriyot")
                        .HasColumnType("int");

                    b.Property<string>("ChassisNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("ContractEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ContractStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Invalidation")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("KmHour")
                        .HasColumnType("int");

                    b.Property<string>("KmHourControl")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoadCapacity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Mark")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Model")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("OwnerCompanyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<string>("Plate")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProportionalLimit")
                        .HasColumnType("int");

                    b.Property<int>("StatusCode")
                        .HasMaxLength(12)
                        .HasColumnType("int");

                    b.Property<string>("TireNotification")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal>("TrailerHeadWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrailerTypeCode")
                        .HasMaxLength(12)
                        .HasColumnType("int");

                    b.Property<string>("UnitId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VehicleAllocationCode")
                        .HasMaxLength(12)
                        .HasColumnType("int");

                    b.Property<int>("VehicleTypeCode")
                        .HasMaxLength(12)
                        .HasColumnType("int");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("VehicleId");

                    b.ToTable("Main", "Vehicle");
                });

            modelBuilder.Entity("HekaLojisticsApp.Entities.Concrete.Vehicle.VehicleInsuranceEntity", b =>
                {
                    b.Property<int>("VehicleInsuranceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CurrencyCode")
                        .HasMaxLength(12)
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsuranceTypeCode")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("KmHour")
                        .HasColumnType("int");

                    b.Property<int>("OperationCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("PersonnelId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VehicePlate")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("VehicleInsuranceId");

                    b.ToTable("Insurance", "Vehicle");
                });

            modelBuilder.Entity("HekaLojisticsApp.Entities.Concrete.Vehicle.VehicleInsuranceTypeEntity", b =>
                {
                    b.Property<int>("VehicleInsuranceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Compulsory")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DefaultPeriyodUnitCode")
                        .HasMaxLength(12)
                        .HasColumnType("int");

                    b.Property<string>("Definition")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VehicleInsuranceTypeId");

                    b.ToTable("InsuranceType", "Vehicle");
                });

            modelBuilder.Entity("HekaLojisticsApp.Entities.Concrete.Vehicle.VehicleNotificationEntity", b =>
                {
                    b.Property<int>("VehicleNotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CareStep")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraNotification")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MailNotification")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmsNotification")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VehicePlate")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("VehicleNotificationId");

                    b.ToTable("Notification", "Vehicle");
                });

            modelBuilder.Entity("HekaLojisticsApp.Entities.Concrete.Vehicle.VehicleTireEntity", b =>
                {
                    b.Property<int>("VehiceTireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimensionsInfo")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("DirectionTypeCode")
                        .HasMaxLength(12)
                        .HasColumnType("int");

                    b.Property<string>("Invalidation")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("KmHour")
                        .HasColumnType("int");

                    b.Property<string>("KmHourControl")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("KmHourLimit")
                        .HasColumnType("int");

                    b.Property<string>("Mark")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Model")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("MontageDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OperationCompanyId")
                        .HasColumnType("int");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("int");

                    b.Property<string>("SeriNo")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VehiceTireTypeCode")
                        .HasMaxLength(12)
                        .HasColumnType("int");

                    b.Property<string>("VehiclePlate")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("VehiceTireId");

                    b.ToTable("Tire", "Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
